version: '3.8'

services:
  nextjs:
    image: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - test-network

  cypress:
    image: cypress-tests
    build:
      context: .
      dockerfile: Dockerfile.cypress
    depends_on:
      - nextjs
    networks:
      - test-network
    environment:
      - CYPRESS_BASE_URL=http://nextjs:3000
    volumes:
      - .:/app

networks:
  test-network:
    driver: bridge
